config/routes.rb
Jmd::Application.routes.draw do
  resources :search, :only => [:index]
  get "/search/reviews" => "reviews#search_reviews", as: :search_reviews
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => {:registrations => "users/registrations",:sessions => "users/sessions", :confirmations => "users/confirmations"}
  root 'welcome#index'

  resources :admin, :only=>[:index]

  match 'searches' => 'admin#searches', via: [:get]
  resources :reviews do
	  resources :comments
  end
  match '/conversions'=> 'companies#conversions', as: :conversions, via: [:get, :post]
  match '/registered'=> 'companies#registered', as: :registered, via: [:get, :post]
  match '/unregistered'=> 'companies#unregistered', as: :unregistered, via: [:get, :post]
  match '/user-review'=> 'companies#user_review', as: :user_review, via: [:get, :post]
  match '/polls-bloopers'=> 'companies#polls_bloopers', as: :polls_bloopers, via: [:get, :post]

	get '/contact_us'=> 'contact_us#new', as: :contact_us

  resources :contact_us,:only => [:new, :create]
  resources :results
  resources :users,:only=>[:update,:edit]
  get '/resources/:slug' => 'resources#show', as: :resource


  match "/profile" => "users#show", via: [:get]
  match "/edit/profile" => "users#edit", via: [:get]
  match "/check_availiblity/user/preferred_alias"=> 'page#check_availiblity', via: [:get]
  get '/industry/companies_by_industry' => "reviews#companies_by_industry"
  get '/company/towns_by_company' => "reviews#towns_by_company"
  get '/town/locations_by_town_and_company' => "reviews#locations_by_town_and_company"
  get "/faqs" => "faqs#index",as: :faqs
  match "/:slug" => "pages#index",via: [:get],as: :page
  resources :polls ,:only => [:show]

  
  namespace :admin do
    resources :maintainences ,:only => [:index] do
      put "/toggle_status" => "maintainences#toggle_status"
    end

    put "/ticket_closed" => "reviews#ticket_closed"
    get "/searches/reviews" => "reviews#search_reviews", as: :search_reviews
    put '/assign_reviews'=> 'reviews#assign_reviews'
    get "change_password" => "users#change_password", as: :change_password
    put "update_password" => "users#update_password", as: :update_password

    get '/industry/companies_by_industry' => "reports#companies_by_industry"
    get '/company/towns_by_company' => "reports#towns_by_company"
    get '/town/locations_by_town_and_company' => "reports#locations_by_town_and_company"

    get '/total_reviews' => "reports#totalreviews"
    get '/nature_of_compliments' => "reports#nature_of_compliments"
    get '/nature_of_complaints2' => "reports#nature_of_complaints2"

    resources :monitor_jagents ,:only => [:index]
    resources :notifications ,:only => [:index]
    resources :customers ,:only => [:index]
  	resources :users
  	resources :locations
  	resources :towns
  	resources :companies
  	resources :industries
  	resources :nature_of_reviews
  	resources :reviews do
      resources :review_notes
      collection do 
        get :archive_reviews
        get :archive_files
      end
      put 'unpublished' => "reviews#unpublished"
  	  resources :comments do
        put 'unpublished_comment' => "comments#unpublished"
      end
  	end
  	resources :addresses
    resources :contact_us, :only => [:index]
  	resources :polls
  	resources :faqs
  	resources :pages, :only => [:index, :edit, :update]
  	resources :resources
  	resources :agents
  	resources :advertises
  	resources :suppliers
  	resources :resource_types
    resources :seos
    resources :company_performances
    resources :abuse_reports
    resources :reports do 
      collection do
        get :industry
        get :company
        get :user_profile
        get :nature_of_complaints
        get :industry_level
        get :supplier_level
        get :supplier_profiles
        get :industry_xls
        get :company_xls
        get :total_xls
        get :all_reviews_xls
        get :all_comments_xls
        get :most_company_xls
        get :registered_company_xls
        get :unregistered_company_xls
        get :archive_data
        get :registered_suppliers
        get :unregistered_suppliers
        get :suppliers_profiles
        get :all_customers
        get :active_customers
        get :conversion_industry
        get :conversion_company
        get :customer_record
        get :sagent
        get :jagent
        get :polls
        get :data_dump
        get :poll
        get :industry_conversion
        get :company_conversion
        get :agent
        get :reviews_processed
        get :agent_output
        get :agent_performance
      
      end
    end
  end
end

app/controllers/admin/addresses_controller.rb
class Admin::AddressesController < AdminController
  before_action :set_address, only: [:show, :edit, :update, :destroy]
	before_action :default_tab
  before_action :new_address, :only => [:create]

  load_and_authorize_resource

  def new_address
    @address = Address.new(address_params)
  end

  def index
    @addresses = Address.includes(:company,:town,:location)
  end

  def new
    @address = Address.new
  end

  def create
    if @address.save
      redirect_to admin_addresses_url, notice: 'Address was successfully created.'
    else
      render :new
    end

  end

  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to admin_addresses_url, notice: 'Address was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @address.destroy
    redirect_to admin_addresses_url
  end

  private
   # Use callbacks to share common setup or constraints between actions.
  def set_address
    @address = Address.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def address_params
    params.require(:address).permit(:location_id,:town_id,:company_id)
  end

	def default_tab
		@active_tab = 'addresses'
	end
end

app/helpers/admin/addresses_helper.rb
module Admin::AddressesHelper
end

app/views/admin/addresses/_form.html.erb
<%= form_for([:admin,@address]) do |f| %>
  <% if @address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% @address.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company %>
    <%= f.collection_select :company_id, Company.order(:industry_id),:id,:title, include_blank: true, required: true%>
  </div>

  <div class="field">
    <%= f.label :town %>
    <%= f.collection_select :town_id, Town.order(:title), :id, :title, include_blank: true ,required: true%>
  </div>

  <div class="field">
    <%= f.label :locations %>
    <%= f.grouped_collection_select :location_id, Town.order(:title), :locations, :title, :id, :title, include_blank: true, required: true%>

  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/admin/addresses/edit.html.erb
<%=render :partial=>'form'%>

app/views/admin/addresses/index.html.erb
<%= link_to "Download Data", admin_addresses_path(params.merge(format: "xls")),:class => "btn btn-primary" if current_user.is? :admin %><br/><br/>
<h1>Addresses</h1>

<table id="addresses" >
  <thead>
    <tr>
      <th>Industry</th>
      <th>Company</th>
      <th>Town</th>
      <th>Location</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.company.industry.title rescue nil %></td>
        <td><%= address.company.title rescue nil %></td>
        <td><%= address.town.try(:title) rescue nil %></td>
        <td><%= address.try(:location).try(:title) rescue nil %></td>

        <td><%= link_to 'Edit', edit_admin_address_path(address) if can? :edit, Address%>
        <%= link_to 'Destroy', [:admin,address], method: :delete, data: { confirm: 'Are you sure?' } if can? :destroy, Address%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address', new_admin_address_path, class: "btn btn-primary" if can? :create, Address%>

app/views/admin/addresses/index.xls.erb
<h1>Addresses</h1>

<table id="addresses" >
  <thead>
    <tr>
      <th>Sr. No.</th>
      <th>Industry</th>
      <th>Company</th>
      <th>Town</th>
      <th>Location</th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each.with_index(1) do |address,index| %>
      <tr>
        <td><%= index %></td>
        <td><%= address.company.industry.title rescue nil %></td>
        <td><%= address.company.title rescue nil %></td>
        <td><%= address.town.try(:title) rescue nil %></td>
        <td><%= address.try(:location).try(:title) rescue nil %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address', new_admin_address_path, class: "btn btn-primary" if can? :create, Address%>

app/views/admin/addresses/new.html.erb
<%=render :partial=>'form'%>