config/routes.rb
Jmd::Application.routes.draw do
  resources :search, :only => [:index]
  get "/search/reviews" => "reviews#search_reviews", as: :search_reviews
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => {:registrations => "users/registrations",:sessions => "users/sessions", :confirmations => "users/confirmations"}
  root 'welcome#index'

  resources :admin, :only=>[:index]

  match 'searches' => 'admin#searches', via: [:get]
  resources :reviews do
	  resources :comments
  end
  match '/conversions'=> 'companies#conversions', as: :conversions, via: [:get, :post]
  match '/registered'=> 'companies#registered', as: :registered, via: [:get, :post]
  match '/unregistered'=> 'companies#unregistered', as: :unregistered, via: [:get, :post]
  match '/user-review'=> 'companies#user_review', as: :user_review, via: [:get, :post]
  match '/polls-bloopers'=> 'companies#polls_bloopers', as: :polls_bloopers, via: [:get, :post]

	get '/contact_us'=> 'contact_us#new', as: :contact_us

  resources :contact_us,:only => [:new, :create]
  resources :results
  resources :users,:only=>[:update,:edit]
  get '/resources/:slug' => 'resources#show', as: :resource


  match "/profile" => "users#show", via: [:get]
  match "/edit/profile" => "users#edit", via: [:get]
  match "/check_availiblity/user/preferred_alias"=> 'page#check_availiblity', via: [:get]
  get '/industry/companies_by_industry' => "reviews#companies_by_industry"
  get '/company/towns_by_company' => "reviews#towns_by_company"
  get '/town/locations_by_town_and_company' => "reviews#locations_by_town_and_company"
  get "/faqs" => "faqs#index",as: :faqs
  match "/:slug" => "pages#index",via: [:get],as: :page
  resources :polls ,:only => [:show]

  
  namespace :admin do
    resources :maintainences ,:only => [:index] do
      put "/toggle_status" => "maintainences#toggle_status"
    end

    put "/ticket_closed" => "reviews#ticket_closed"
    get "/searches/reviews" => "reviews#search_reviews", as: :search_reviews
    put '/assign_reviews'=> 'reviews#assign_reviews'
    get "change_password" => "users#change_password", as: :change_password
    put "update_password" => "users#update_password", as: :update_password

    get '/industry/companies_by_industry' => "reports#companies_by_industry"
    get '/company/towns_by_company' => "reports#towns_by_company"
    get '/town/locations_by_town_and_company' => "reports#locations_by_town_and_company"

    get '/total_reviews' => "reports#totalreviews"
    get '/nature_of_compliments' => "reports#nature_of_compliments"
    get '/nature_of_complaints2' => "reports#nature_of_complaints2"

    resources :monitor_jagents ,:only => [:index]
    resources :notifications ,:only => [:index]
    resources :customers ,:only => [:index]
  	resources :users
  	resources :locations
  	resources :towns
  	resources :companies
  	resources :industries
  	resources :nature_of_reviews
  	resources :reviews do
      resources :review_notes
      collection do 
        get :archive_reviews
        get :archive_files
      end
      put 'unpublished' => "reviews#unpublished"
  	  resources :comments do
        put 'unpublished_comment' => "comments#unpublished"
      end
  	end
  	resources :addresses
    resources :contact_us, :only => [:index]
  	resources :polls
  	resources :faqs
  	resources :pages, :only => [:index, :edit, :update]
  	resources :resources
  	resources :agents
  	resources :advertises
  	resources :suppliers
  	resources :resource_types
    resources :seos
    resources :company_performances
    resources :abuse_reports
    resources :reports do 
      collection do
        get :industry
        get :company
        get :user_profile
        get :nature_of_complaints
        get :industry_level
        get :supplier_level
        get :supplier_profiles
        get :industry_xls
        get :company_xls
        get :total_xls
        get :all_reviews_xls
        get :all_comments_xls
        get :most_company_xls
        get :registered_company_xls
        get :unregistered_company_xls
        get :archive_data
        get :registered_suppliers
        get :unregistered_suppliers
        get :suppliers_profiles
        get :all_customers
        get :active_customers
        get :conversion_industry
        get :conversion_company
        get :customer_record
        get :sagent
        get :jagent
        get :polls
        get :data_dump
        get :poll
        get :industry_conversion
        get :company_conversion
        get :agent
        get :reviews_processed
        get :agent_output
        get :agent_performance
      
      end
    end
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
	validates :title, :town_id, presence: true
	validates :title, :uniqueness => { :scope => :town_id }

	has_many :addresses
	belongs_to :town
	has_many :reviews
	
  def self.search(search)
    search_condition = "%" + search + "%"
    find(:all, :conditions => ['title LIKE ?', search_condition])
  end

end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < AdminController
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  before_action :get_defaults
  before_action :default_tab
  before_action :new_location, :only => [:create]

  load_and_authorize_resource

  def new_location
    @location = Location.new(location_params)
  end

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.includes(:town)
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    respond_to do |format|
      if @location.save
        format.html { redirect_to [:admin,@location], notice: 'Location was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to [:admin,@location], notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to admin_locations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:title, :user_id,:town_id)
    end

    def get_defaults
      @towns = Town.all
    end

    def default_tab
    	@active_tab = 'locations'
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/admin/locations/_form.html.erb
<%= form_for([:admin,@location]) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title ,required: true%>
  </div>
  <div class="field">
    <%= f.label :town %>
    <%= f.select :town_id, @towns.map { |town| [town.title,town.id] }  ,required: true%>
  </div>

  <div class="field">
    <%= f.hidden_field :user_id ,:value=>current_user.id  %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/admin/locations/edit.html.erb
<%= render 'form' %>

app/views/admin/locations/index.html.erb
<h1>Locations</h1>

<table id="locations" >
  <thead>
    <tr>
      <th>Title</th>
      <th>Town</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.title %></td>
        <td><%= location.town.title rescue nil %></td>

        <td><%= link_to 'Edit', edit_admin_location_path(location)  if can? :edit, Location%>
        <%= link_to 'Destroy', [:admin,location], method: :delete, data: { confirm: 'Are you sure?' }  if can? :destroy, Location%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_admin_location_path, class: "btn btn-primary"  if can? :create, Location%>

app/views/admin/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_locations_path %>

app/views/admin/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @location.title %>
</p>

<p>
  <strong>Town:</strong>
  <%= @location.town.title %>
</p>

<%= link_to 'Edit', edit_admin_location_path(@location)  if can? :edit, Location%>
<%= link_to 'New', new_admin_location_path  if can? :create, Location%>