config/routes.rb
Jmd::Application.routes.draw do
  resources :search, :only => [:index]
  get "/search/reviews" => "reviews#search_reviews", as: :search_reviews
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => {:registrations => "users/registrations",:sessions => "users/sessions", :confirmations => "users/confirmations"}
  root 'welcome#index'

  resources :admin, :only=>[:index]

  match 'searches' => 'admin#searches', via: [:get]
  resources :reviews do
	  resources :comments
  end
  match '/conversions'=> 'companies#conversions', as: :conversions, via: [:get, :post]
  match '/registered'=> 'companies#registered', as: :registered, via: [:get, :post]
  match '/unregistered'=> 'companies#unregistered', as: :unregistered, via: [:get, :post]
  match '/user-review'=> 'companies#user_review', as: :user_review, via: [:get, :post]
  match '/polls-bloopers'=> 'companies#polls_bloopers', as: :polls_bloopers, via: [:get, :post]

	get '/contact_us'=> 'contact_us#new', as: :contact_us

  resources :contact_us,:only => [:new, :create]
  resources :results
  resources :users,:only=>[:update,:edit]
  get '/resources/:slug' => 'resources#show', as: :resource


  match "/profile" => "users#show", via: [:get]
  match "/edit/profile" => "users#edit", via: [:get]
  match "/check_availiblity/user/preferred_alias"=> 'page#check_availiblity', via: [:get]
  get '/industry/companies_by_industry' => "reviews#companies_by_industry"
  get '/company/towns_by_company' => "reviews#towns_by_company"
  get '/town/locations_by_town_and_company' => "reviews#locations_by_town_and_company"
  get "/faqs" => "faqs#index",as: :faqs
  match "/:slug" => "pages#index",via: [:get],as: :page
  resources :polls ,:only => [:show]

  
  namespace :admin do
    resources :maintainences ,:only => [:index] do
      put "/toggle_status" => "maintainences#toggle_status"
    end

    put "/ticket_closed" => "reviews#ticket_closed"
    get "/searches/reviews" => "reviews#search_reviews", as: :search_reviews
    put '/assign_reviews'=> 'reviews#assign_reviews'
    get "change_password" => "users#change_password", as: :change_password
    put "update_password" => "users#update_password", as: :update_password

    get '/industry/companies_by_industry' => "reports#companies_by_industry"
    get '/company/towns_by_company' => "reports#towns_by_company"
    get '/town/locations_by_town_and_company' => "reports#locations_by_town_and_company"

    get '/total_reviews' => "reports#totalreviews"
    get '/nature_of_compliments' => "reports#nature_of_compliments"
    get '/nature_of_complaints2' => "reports#nature_of_complaints2"

    resources :monitor_jagents ,:only => [:index]
    resources :notifications ,:only => [:index]
    resources :customers ,:only => [:index]
  	resources :users
  	resources :locations
  	resources :towns
  	resources :companies
  	resources :industries
  	resources :nature_of_reviews
  	resources :reviews do
      resources :review_notes
      collection do 
        get :archive_reviews
        get :archive_files
      end
      put 'unpublished' => "reviews#unpublished"
  	  resources :comments do
        put 'unpublished_comment' => "comments#unpublished"
      end
  	end
  	resources :addresses
    resources :contact_us, :only => [:index]
  	resources :polls
  	resources :faqs
  	resources :pages, :only => [:index, :edit, :update]
  	resources :resources
  	resources :agents
  	resources :advertises
  	resources :suppliers
  	resources :resource_types
    resources :seos
    resources :company_performances
    resources :abuse_reports
    resources :reports do 
      collection do
        get :industry
        get :company
        get :user_profile
        get :nature_of_complaints
        get :industry_level
        get :supplier_level
        get :supplier_profiles
        get :industry_xls
        get :company_xls
        get :total_xls
        get :all_reviews_xls
        get :all_comments_xls
        get :most_company_xls
        get :registered_company_xls
        get :unregistered_company_xls
        get :archive_data
        get :registered_suppliers
        get :unregistered_suppliers
        get :suppliers_profiles
        get :all_customers
        get :active_customers
        get :conversion_industry
        get :conversion_company
        get :customer_record
        get :sagent
        get :jagent
        get :polls
        get :data_dump
        get :poll
        get :industry_conversion
        get :company_conversion
        get :agent
        get :reviews_processed
        get :agent_output
        get :agent_performance
      
      end
    end
  end
end

app/models/town.rb
class Town < ActiveRecord::Base
	validates :title, presence: true
	has_many :locations
	has_many :reviews
	
  def self.search(search)
    search_condition = "%" + search + "%"
    find(:all, :conditions => ['title LIKE ?', search_condition])
  end

end

app/controllers/admin/towns_controller.rb
class Admin::TownsController < AdminController
	before_action :set_town, only: [:show, :edit, :update, :destroy]
	before_action :default_tab
  before_action :new_town, :only => [:create]
  load_and_authorize_resource

  def new_town
    @town = Town.new(town_params)
  end

  # GET /towns
  # GET /towns.json
  def index
    @towns = Town.all
  end

  # GET /towns/1
  # GET /towns/1.json
  def show
  end

  # GET /towns/new
  def new
    @town = Town.new
  end

  # GET /towns/1/edit
  def edit
  end

  # POST /towns
  # POST /towns.json
  def create
    respond_to do |format|
      if @town.save
        format.html { redirect_to [:admin,@town], notice: 'Town was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /towns/1
  # PATCH/PUT /towns/1.json
  def update
		if @town.update(town_params)
		  redirect_to admin_towns_url, notice: 'Town was successfully updated.'
		else
		  render action: 'edit'
		end
  end

  # DELETE /towns/1
  # DELETE /towns/1.json
  def destroy
    @town.destroy
  	redirect_to admin_towns_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_town
      @town = Town.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def town_params
    	puts params
      params.require(:town).permit(:title, :user_id)
    end

    def default_tab
    	@active_tab = 'towns'
    end
end

app/helpers/towns_helper.rb
module TownsHelper
end

app/views/admin/towns/_form.html.erb
<%= form_for([:admin,@town]) do |f| %>
  <% if @town.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@town.errors.count, "error") %> prohibited this town from being saved:</h2>

      <ul>
      <% @town.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title ,required: true %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id ,:value=>current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/admin/towns/edit.html.erb
<%= render 'form' %>

app/views/admin/towns/index.html.erb
<h1>Towns</h1>

<table id="towns" >
  <thead>
    <tr>
      <th>Title</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @towns.each do |town| %>
      <tr>
        <td><%= town.title %></td>
        <td><%= link_to 'Edit', edit_admin_town_path(town) if can? :edit, Town%>
        <%= link_to 'Destroy', [:admin,town], method: :delete, data: { confirm: 'Are you sure?' } if can? :destroy, Town%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Town', new_admin_town_path, class: "btn btn-primary" if can? :create, Town%>

app/views/admin/towns/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_towns_path %>

app/views/admin/towns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @town.title %>
</p>

<%= link_to 'Edit', edit_admin_town_path(@town) if can? :edit, Town%>