config/routes.rb
Jmd::Application.routes.draw do
  resources :search, :only => [:index]
  get "/search/reviews" => "reviews#search_reviews", as: :search_reviews
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => {:registrations => "users/registrations",:sessions => "users/sessions", :confirmations => "users/confirmations"}
  root 'welcome#index'

  resources :admin, :only=>[:index]

  match 'searches' => 'admin#searches', via: [:get]
  resources :reviews do
	  resources :comments
  end
  match '/conversions'=> 'companies#conversions', as: :conversions, via: [:get, :post]
  match '/registered'=> 'companies#registered', as: :registered, via: [:get, :post]
  match '/unregistered'=> 'companies#unregistered', as: :unregistered, via: [:get, :post]
  match '/user-review'=> 'companies#user_review', as: :user_review, via: [:get, :post]
  match '/polls-bloopers'=> 'companies#polls_bloopers', as: :polls_bloopers, via: [:get, :post]

	get '/contact_us'=> 'contact_us#new', as: :contact_us

  resources :contact_us,:only => [:new, :create]
  resources :results
  resources :users,:only=>[:update,:edit]
  get '/resources/:slug' => 'resources#show', as: :resource


  match "/profile" => "users#show", via: [:get]
  match "/edit/profile" => "users#edit", via: [:get]
  match "/check_availiblity/user/preferred_alias"=> 'page#check_availiblity', via: [:get]
  get '/industry/companies_by_industry' => "reviews#companies_by_industry"
  get '/company/towns_by_company' => "reviews#towns_by_company"
  get '/town/locations_by_town_and_company' => "reviews#locations_by_town_and_company"
  get "/faqs" => "faqs#index",as: :faqs
  match "/:slug" => "pages#index",via: [:get],as: :page
  resources :polls ,:only => [:show]

  
  namespace :admin do
    resources :maintainences ,:only => [:index] do
      put "/toggle_status" => "maintainences#toggle_status"
    end

    put "/ticket_closed" => "reviews#ticket_closed"
    get "/searches/reviews" => "reviews#search_reviews", as: :search_reviews
    put '/assign_reviews'=> 'reviews#assign_reviews'
    get "change_password" => "users#change_password", as: :change_password
    put "update_password" => "users#update_password", as: :update_password

    get '/industry/companies_by_industry' => "reports#companies_by_industry"
    get '/company/towns_by_company' => "reports#towns_by_company"
    get '/town/locations_by_town_and_company' => "reports#locations_by_town_and_company"

    get '/total_reviews' => "reports#totalreviews"
    get '/nature_of_compliments' => "reports#nature_of_compliments"
    get '/nature_of_complaints2' => "reports#nature_of_complaints2"

    resources :monitor_jagents ,:only => [:index]
    resources :notifications ,:only => [:index]
    resources :customers ,:only => [:index]
  	resources :users
  	resources :locations
  	resources :towns
  	resources :companies
  	resources :industries
  	resources :nature_of_reviews
  	resources :reviews do
      resources :review_notes
      collection do 
        get :archive_reviews
        get :archive_files
      end
      put 'unpublished' => "reviews#unpublished"
  	  resources :comments do
        put 'unpublished_comment' => "comments#unpublished"
      end
  	end
  	resources :addresses
    resources :contact_us, :only => [:index]
  	resources :polls
  	resources :faqs
  	resources :pages, :only => [:index, :edit, :update]
  	resources :resources
  	resources :agents
  	resources :advertises
  	resources :suppliers
  	resources :resource_types
    resources :seos
    resources :company_performances
    resources :abuse_reports
    resources :reports do 
      collection do
        get :industry
        get :company
        get :user_profile
        get :nature_of_complaints
        get :industry_level
        get :supplier_level
        get :supplier_profiles
        get :industry_xls
        get :company_xls
        get :total_xls
        get :all_reviews_xls
        get :all_comments_xls
        get :most_company_xls
        get :registered_company_xls
        get :unregistered_company_xls
        get :archive_data
        get :registered_suppliers
        get :unregistered_suppliers
        get :suppliers_profiles
        get :all_customers
        get :active_customers
        get :conversion_industry
        get :conversion_company
        get :customer_record
        get :sagent
        get :jagent
        get :polls
        get :data_dump
        get :poll
        get :industry_conversion
        get :company_conversion
        get :agent
        get :reviews_processed
        get :agent_output
        get :agent_performance
      
      end
    end
  end
end

app/helpers/admin/reports_helper.rb
module Admin::ReportsHelper
    def total_reviews
		#total reviews according to compliment and complaints
		@compliments = Review.where('Date(created_at) >= ? and Date(created_at) <= ? and user_id is not null and review_type = ? and ispublished = ? and archive = ?', 1.year.ago, Date.today,'compliment',true,false)  rescue nil
		@complaints = Review.where('Date(created_at) >= ? and Date(created_at) <= ? and user_id is not null and review_type = ? and ispublished = ? and archive = ?', 1.year.ago, Date.today,'complaint',true,false	)  rescue nil
		@total_converted = Review.where('Date(created_at) >= ? and Date(created_at) <= ? and user_id is not null and review_type = ? and change_date is not null', 1.year.ago, Date.today,'compliment')  rescue nil
	end

	def all_reviews_xls
		@reviews = Review.where("user_id is not null")
	end

	def all_comments_xls
		@comments = Comment.all
	end

	def nature_of_complaints
		@nature_of_compliments = []
		NatureOfReview.where("review_type = ?","compliment").pluck(:title).each do |r|
			@nature_of_compliments << [r,Review.nature_count(r).count]
		end
		@n = @nature_of_compliments
		@n = Hash[*@n.flatten]

		@nature_of_complaints = []
		NatureOfReview.where("review_type = ?","complaint").pluck(:title).each do |r|
			@nature_of_complaints << [r,Review.nature_count(r).count]
		end
		@n1 = @nature_of_complaints
		@n1 = Hash[*@n1.flatten]

	end

  def nature_of_complaint_common
    @nature_of_compliments = []
    NatureOfReview.where("review_type = ?","compliment").pluck(:title).each do |r|
      @nature_of_compliments << Review.nature_count(r)
    end
    @reviews = @nature_of_compliments
  
    @nature_of_complaints = []
    NatureOfReview.where("review_type = ?","complaint").pluck(:title).each do |r|
      @nature_of_complaints << Review.nature_count(r)
    end
    @reviews1 = @nature_of_complaints
  end 




	def total_reviews_dump
		#total reviews according to compliment and complaints
		@compliments = Review.where('user_id is not null and review_type = ?','compliment')  rescue nil
		@complaints = Review.where('user_id is not null and review_type = ?', 'complaint')  rescue nil
		@total_converted = Review.where('user_id is not null and review_type = ? and change_date is not null','compliment')  rescue nil
	end

	def nature_of_complaints_dump
		#nature of review for compliments
		@billing = Review.where('user_id is not null and nature_of_review = ? and review_type = ? ','Billing/accounts', 'compliment') rescue nil
		@booking = Review.where('user_id is not null and nature_of_review = ? and review_type = ? ','Booking', 'compliment') rescue nil
		@call_center = Review.where('user_id is not null and nature_of_review = ? and review_type = ? ','Call centre efficiency', 'compliment') rescue nil
		@contract = Review.where('user_id is not null and nature_of_review = ? and review_type = ? ','Contract', 'compliment') rescue nil
		@delivery = Review.where('user_id is not null and nature_of_review = ? and review_type = ? ','Delivery on time', 'compliment') rescue nil
		@feedback = Review.where('user_id is not null and nature_of_review = ? and review_type = ?','Feedback', 'compliment') rescue nil
		@going_extra = Review.where('user_id is not null and nature_of_review = ? and review_type = ? ','Going the extra mile', 'compliment') rescue nil
		@great_attitude = Review.where('user_id is not null and nature_of_review = ? and review_type = ? ','Great attitude', 'compliment') rescue nil
		@pricing = Review.where('user_id is not null and nature_of_review = ? and review_type = ? ','Pricing', 'compliment') rescue nil
		@refund = Review.where('user_id is not null and nature_of_review = ? and review_type = ? ','Refund', 'compliment') rescue nil
		@repairs = Review.where('user_id is not null and nature_of_review = ? and review_type = ? ','Repairs', 'compliment') rescue nil
		@stock = Review.where('user_id is not null and nature_of_review = ? and review_type = ? ','Stock', 'compliment') rescue nil
		@others = Review.where('user_id is not null and nature_of_review = ? and review_type = ? ','Other', 'compliment') rescue nil

		#nature of review for complaints
		@bad_attitude = Review.where('user_id is not null and nature_of_review = ? and review_type = ?','Bad attitude', 'complaint') rescue nil
		@billing_account = Review.where('user_id is not null and nature_of_review = ? and review_type = ? ','Billing/Accounts', 'complaint') rescue nil
		@booking_query = Review.where('user_id is not null and nature_of_review = ? and review_type = ? ','Booking query', 'complaint') rescue nil
		@breach_of_contract = Review.where('user_id is not null and nature_of_review = ? and review_type = ? ','Breach of contract', 'complaint') rescue nil
		@call_centre_c = Review.where('user_id is not null and nature_of_review = ? and review_type = ? ','Call centre', 'complaint') rescue nil
		@damaged_goods = Review.where('user_id is not null and nature_of_review = ? and review_type = ? ','Damaged goods', 'complaint') rescue nil
		@expiry = Review.where('user_id is not null and nature_of_review = ? and review_type = ? ','Expiry date', 'complaint') rescue nil
		@feedback_response = Review.where('user_id is not null and nature_of_review = ? and review_type = ? ','Feedback/response', 'complaint') rescue nil
		@hygiene = Review.where('user_id is not null and nature_of_review = ? and review_type = ?','Hygiene', 'complaint') rescue nil
		@Late_no_delivery = Review.where('user_id is not null and nature_of_review = ? and review_type = ?','Late/no delivery', 'complaint') rescue nil
		@out_of_stock = Review.where('user_id is not null and nature_of_review = ? and review_type = ? ','Out of stock', 'complaint') rescue nil
		@pricing_bar_codes = Review.where('user_id is not null and nature_of_review = ? and review_type = ? ','Pricing/bar codes', 'complaint') rescue nil
		@repairs_servicing = Review.where('user_id is not null and nature_of_review = ? and review_type = ? ','Repairs/servicing', 'complaint') rescue nil
		@spam = Review.where('user_id is not null and nature_of_review = ? and review_type = ? ','Spam', 'complaint') rescue nil
		@others_c = Review.where('user_id is not null and nature_of_review = ? and review_type = ? ','Other', 'complaint') rescue nil
	end

	def industry_level #industries
		@industry = Industry.where('id = ?', params[:industry]).first
		
		#total number of complaints/compliments according to each industry
		@compliments = Review.where('Date(created_at) >= ? and Date(created_at) <= ? and user_id is not null and industry_id = ? and review_type = ?',1.year.ago, Date.today,@industry.id, 'compliment').count
		@complaints = Review.where('Date(created_at) >= ? and Date(created_at) <= ? and user_id is not null and industry_id = ? and review_type = ?',1.year.ago, Date.today,@industry.id, 'complaint').count
        #total number of compliments and complaints according to the nature of review
        @nature_of_compliments = []
		NatureOfReview.where("review_type = ?","compliment").pluck(:title).each do |r|
			@nature_of_compliments << [r,Review.nature_count2(@industry.id,r).count]
		end
		@n = @nature_of_compliments
		@n = Hash[*@n.flatten]

		@nature_of_complaints = []
		NatureOfReview.where("review_type = ?","complaint").pluck(:title).each do |r|
			@nature_of_complaints << [r,Review.nature_count2(@industry.id,r).count]
		end
		@n1 = @nature_of_complaints
		@n1 = Hash[*@n1.flatten]
        
        send_data(render_to_string(:template=>"admin/reports/industry_level.html.erb" ) , :type=>"text/xls",:filename => "customer_summary.xls")
	end

   def supplier_level #company/suppliers
   	    @company = Company.where('id = ?', params[:company]).first
   	    
		#total number of complaints/compliments according to each industry
		@compliments = Review.where('Date(created_at) >= ? and Date(created_at) <= ? and user_id is not null and company_id = ? and review_type = ?',1.year.ago, Date.today,@company.id, 'compliment').count rescue nil
		@complaints = Review.where('Date(created_at) >= ? and Date(created_at) <= ? and user_id is not null and company_id = ? and review_type = ?',1.year.ago, Date.today,@company.id, 'complaint').count rescue nil
        #total number of compliments and complaints according to the nature of review
          @nature_of_compliments = []
		NatureOfReview.where("review_type = ?","compliment").pluck(:title).each do |r|
			@nature_of_compliments << [r,Review.nature_count3(@company.id,r).count]
		end
		@n = @nature_of_compliments
		@n = Hash[*@n.flatten]

		@nature_of_complaints = []
		NatureOfReview.where("review_type = ?","complaint").pluck(:title).each do |r|
			@nature_of_complaints << [r,Review.nature_count3(@company.id,r).count]
		end
		@n1 = @nature_of_complaints
		@n1 = Hash[*@n1.flatten]
        
        send_data(render_to_string(:template=>"admin/reports/supplier_level.html.erb" ) , :type=>"text/xls",:filename => "supplier_info.xls")
    end

   def most_compliments
   	    @most_compliment = Review.select(:company_id).where('Date(created_at) >= ? and Date(created_at) <= ? and review_type = ? and user_id is not null',1.year.ago, Date.today, 'compliment').map(&:company_id) rescue nil
   	    freq = @most_compliment.inject(Hash.new(0)) { |h,v| h[v] += 1; h }
   	    @value_compliments = @most_compliment.max_by { |v| freq[v] }
   	    @max_compliment = freq.values.max
   	 
        # Most complaints for supplier
   	    @most_complaint = Review.select(:company_id).where('Date(created_at) >= ? and Date(created_at) <= ? and review_type = ? and user_id is not null',1.year.ago, Date.today, 'complaint').map(&:company_id) rescue nil
   	    freq = @most_complaint.inject(Hash.new(0)) { |h,v| h[v] += 1; h }
   	    @value_complaints = @most_complaint.max_by { |v| freq[v] }
   	    @max_complaint = freq.values.max
   end

   def all_customers 
      if params[:subaction] == "all_customer"
   	  	@start_from = params[:report1][:start_date] rescue ""
   	  	@start_to = params[:report1][:end_date] rescue ""

app/views/admin/reports/all_comments_xls.xls.erb
<table>
	<tr>
		<th>Sr. No.</th>
		<th>Date</th>
		<th>Ticket Number</th>
		<th>Comment</th>
		<th>Customer Name</th>
		<th>Customer Email</th>
		<th>Company Name</th>
	</tr>
	<% @comments.each.with_index(1) do |comment,index| %>
	<tr>
		<td><%= index %></td>
		<td><%= comment.created_at.strftime("%d/%m/%Y") rescue nil%></td>
		<td><%= comment.review.ticket_number rescue nil%></td>
		<td><%= comment.title.html_safe rescue nil%></td>
		<td><%= comment.name rescue nil%></td>
		<td><%= comment.email rescue nil%></td>
		<td><%= comment.review.company.title rescue nil%></td>
	</tr>
	<% end %>
	
</table>

app/views/admin/reports/all_customers.html.erb
<h4>All Customers</h4>
	<table id="customers">
		<thead>
		  <tr>
		    <th>Sr. No. </th>
		    <th width="15%">First Name</th>
		    <th width="15%">Last Name</th>
		    <th width="30%">Email</th>
		    <th width="20%">Email Confirmation</th>
		    <th width="20%">Preferred Alias</th>
		    <th width="20%">Age</th>
		    <th width="20%">Gender</th>
		    <th width="20%">Address line 1</th>
		    <th width="20%">Address line 2</th>
		    <th width="20%">Town</th>
		    <th width="20%">country</th>
		    <th width="20%">Lives in</th>
		    <th width="20%">Code</th>
		  </tr>
		</thead>

		<tbody>
		  <% @customers.each_with_index.each do |user,i| %>
		    <tr>
		      <td><%= i+1 %></td>
		      <td><%=user.first_name rescue nil%></td>
		      <td><%=user.last_name rescue nil%></td>
		      <td><%=user.email rescue nil%></td>
		      <td><%=user.confirmed_at.present? ? 'Confirmed' : 'Pending'%></td>
		      <td><%=user.preferred_alias rescue nil%></td>
		      <td><%=user.age%></td>
		      <td><% if user.gender == '1' %>
				    <%="Male"%>
				    <%else%>
				    <%="Female"%>
				    <%end%>
			  </td>
		      <td><%=user.address_line1 rescue nil%></td>
		      <td><%=user.address_line2 rescue nil%></td>
		      <td><%=user.town rescue nil%></td>
		      <td><%=user.country rescue nil%></td>
		      <td><%=user.lives_in rescue nil%></td>
		      <td><%=user.postal_code rescue nil%></td>
		    </tr>
		  <% end %>
		</tbody>
	</table>
<br/><br/>

app/views/admin/reports/index.html.erb
<%= render 'tab' %>
</br>
<strong>Download Data for 12 Months period (From <%= (1.year.ago).strftime('%d-%m-%Y')%>  to  <%= (Date.today).strftime('%d-%m-%Y')%>)</strong></br></br>
<%= link_to image_tag('/assets/excel.png', :border=>"0", :align=>"absmiddle") + "Summary of reviews Excel", customer_record_admin_reports_path%><br/>
<%= link_to image_tag('/assets/excel.png', :border=>"0", :align=>"absmiddle") + "Industry conversion stats", conversion_industry_admin_reports_path(params.merge(format: "xls")), :method=> :get%><br/>
<%= link_to image_tag('/assets/excel.png', :border=>"0", :align=>"absmiddle") + "Supplier conversion stats", conversion_company_admin_reports_path(params.merge(format: "xls")), :method=> :get%><br/>
<%= link_to image_tag('/assets/excel.png', :border=>"0", :align=>"absmiddle") + "Customer Details", all_customers_admin_reports_path(params.merge(format: "xls")), :method=> :get%><br/>

<%= link_to image_tag('/assets/excel.png', :border=>"0", :align=>"absmiddle") + "Junior Agents", jagent_admin_reports_path(params.merge(format: "xls")), :method=> :get%><br/>
<%= link_to image_tag('/assets/excel.png', :border=>"0", :align=>"absmiddle") + "Senior Agents", sagent_admin_reports_path(params.merge(format: "xls")), :method=> :get%><br/>
<%= link_to image_tag('/assets/excel.png', :border=>"0", :align=>"absmiddle") + "Active Customers (6 Months)", active_customers_admin_reports_path(params.merge(format: "xls")), :method=> :get%><br/>
<%= link_to image_tag('/assets/excel.png', :border=>"0", :align=>"absmiddle") + "Suppliers Profiles", suppliers_profiles_admin_reports_path(params.merge(format: "xls")), :method=> :get%><br/>
<%= link_to image_tag('/assets/excel.png', :border=>"0", :align=>"absmiddle") + "Industry xls", industry_xls_admin_reports_path%><br/>
<%= link_to image_tag('/assets/excel.png', :border=>"0", :align=>"absmiddle") + "Company/Supplier xls", company_xls_admin_reports_path(params.merge(format: "xls")), :method=> :get%><br/>
<%= link_to image_tag('/assets/excel.png', :border=>"0", :align=>"absmiddle") + "Total reviews", total_xls_admin_reports_path%><br/>
<%= link_to image_tag('/assets/excel.png', :border=>"0", :align=>"absmiddle") + "Most complaints/compliments",most_company_xls_admin_reports_path%><br/>
<%= link_to image_tag('/assets/excel.png', :border=>"0", :align=>"absmiddle") + "List Of Registered Suppliers", registered_suppliers_admin_reports_path(params.merge(format: "xls")), :method=> :get %><br/>
<%= link_to image_tag('/assets/excel.png', :border=>"0", :align=>"absmiddle") + "List Of Unregistered Suppliers", unregistered_suppliers_admin_reports_path(params.merge(format: "xls")), :method=> :get %>
<br/>
<%= link_to image_tag('/assets/excel.png', :border=>"0", :align=>"absmiddle") + "Download Poll Results(12 months)", polls_admin_reports_path(params.merge(format: "xls")), :method=> :get %>
<br/>
<%= link_to image_tag('/assets/excel.png', :border=>"0", :align=>"absmiddle") + "Download reviews processed by each agent (12 months)", reviews_processed_admin_reports_path(params.merge(format: "xls")), :method=> :get %>
<br/>
<%= link_to image_tag('/assets/excel.png', :border=>"0", :align=>"absmiddle") + "Download accuracy of agents output (12 months)", agent_output_admin_reports_path(params.merge(format: "xls")), :method=> :get %>
<br/>
<%= link_to image_tag('/assets/excel.png', :border=>"0", :align=>"absmiddle") + "Download Agents performance (12 months)", agent_performance_admin_reports_path(params.merge(format: "xls")), :method=> :get %>
<br/>

<br/><br/>


<table>
<%= form_for :report, :url=> admin_reports_path, :method => :get do |f| %>
  <h2>Filter Data</h2>
    <tr>
    <div class="review_form">
			<div class="name_lft">Industry: </div>
			<div class="small-input2">
			  <%= f.collection_select :industry_id, Industry.order(:title) + [Industry.new(:id => Industry.last.id,:title => "Other")], :id,:title,{:include_blank=>"Select Industry"},:rel => "/admin/industry/companies_by_industry",   onchange: 'CheckOther();'%>
			  <input type="text" id="other_type" name="other_type"><br/>
			</div>

		</div>

		<div class="review_form">
			<div class="name_lft">Company: </div>
			<div class="small-input2">
			    <%= f.collection_select :company_id, @companies, :id, :title,  {:include_blank=>"Select Company"}, :rel => "/admin/company/towns_by_company"%>
		    <input type="text" id="txt_report_company_id" name="txt_report_company_id"><br>

			</div>
		</div>

		<div class="review_form">
			<div class="name_lft">Town: </div>
			<div class="small-input2">
			   <%= f.collection_select :town_id, @towns+ [Industry.new(:id => Town.last.id + 1,:title => "Other")], :id, :title, {:include_blank=>"Select Town"}, :rel => "/admin/town/locations_by_town_and_company"%>
			   <!-- <input type="text" id="txt_review_town_id" name="txt_review_town_id"><br> -->
			   	<input type="text" id="other_town" name="txt_report_town_id"><br>
			</div>

		</div>

		<div class="review_form">
			<div class="name_lft">Location: </div>
			<div class="small-input2">
			   <%= f.collection_select :location_id, @locations ,:id ,:title, {:include_blank=>"Select Location"}%>
			   	<input type="text" id="txt_report_location_id" name="txt_report_location_id"><br>
			</div>
		</div>

   <tr>
     <td>Review Type</td>
   	 <td><%= f.select :review_type, (options_for_select([['Select Review Type', ''],['Compliment', 'compliment'], ['Complaint', 'complaint']],selected: :review_type))%></td>
   </tr>
   <tr><strong>Choose Nature Of Review according to Review Type</strong></tr>
   <tr>
   	 <td>Nature of Review (Compliment)</td>
   	 <td><%= f.select :nature_of_review_eq, NatureOfReview.where('review_type = ?', 'compliment').map{|s| [s.title, s.title]}, {:prompt => "Select Nature Of Review"}%></td>

     <td>Nature of Review (Complaint)</td>
   	 <td><%= f.select :nature_of_review_eq, NatureOfReview.where('review_type = ?', 'complaint').map{|s| [s.title, s.title]}, {:prompt => "Select Nature Of Review"}%></td>

   </tr>
   <td><%= button_tag  :submit ,name:"subaction",value: "update",:class => "btn btn btn-primary" %></td>
   
<%end%>
</table>
<br/><br/>

<%if params[:subaction] == "update"%>

<%unless @reviews.blank?%>
   <%= link_to "Download Filter Data", admin_reports_path(params.merge(format: "xls")), :method=> :get, :class => "btn btn-primary" %>
<%end%>
<h4>Reviews</h4>

<table id="admin_review_xls" >
	<thead>
	  <tr>
			<th width="10%">Date</th>
			<th width="15%">Ticket Number</th>
			<th width="10%">Review</th>
			<th width="15%">Company</th>
			<th width="15%">Title</th>
	        <th width="15%">Customer Name</th>
	  </tr>
	</thead>

	<tbody>
	  <% @reviews.each do |review| %>
	    <tr>
				<td><%=review.created_at.strftime("%d/%m/%Y | %H:%M") rescue nil %></td>
				<td><%=review.ticket_number rescue nil %></td>
				<td><%=review.review_type.titleize rescue nil %></td>
				<td><%=review.company.title.titleize rescue nil %></td>
				<td><%=review.title.titleize rescue nil %></td>
			    <td><%=review.try(:user).try(:full_name) rescue nil%></td>
	    </tr>
	  <% end %>
	</tbody>	
</table>
<%end%>



<h1>Totals – over a 12 month period (From <%= (1.year.ago).strftime('%d-%m-%Y')%>  to  <%= (Date.today).strftime('%d-%m-%Y')%>)</h1>
<%= link_to "Download Excel",admin_total_reviews_path(params.merge(format: "xls")), :method=> :get, :class => "btn btn-primary"  %>
<table id="total_compliment">

	<thead>
		<tr>
			<th>Total Reviews</th>
			<th>Total Count</th>
		</tr>

	</thead>

	<tbody>
		<tr>
			<td>Compliments</td>
			<td><%= @compliments.count rescue nil%></td>
		</tr>
		<tr>
			<td>Complaint</td>
			<td><%= @complaints.count rescue nil%></td>
		</tr>
		<tr>
			<td><strong>Total</strong></td>
			<td><%= @complaints.count + @compliments.count%></td>
		</tr>

	</tbody>
</table>

<br/><br/>
<div>
<%= link_to "Download Excel",admin_nature_of_compliments_path(params.merge(format: "xls")), :method=> :get, :class => "btn btn-primary"  %>
<table id="compliments">
	<thead>
		<tr>
			<th>Nature of Compliment</th>
			<th>Total</th>
		</tr>

	</thead>

	<tbody>
		<% @n.each do |r| %>
		<tr>
			<td><%= r[0] %></td>
			<td><%= r[1] %></td>
		</tr>
		<% end %>
		

	</tbody>
</table>
</div>
<br/><br/>
<div>
	<%= link_to "Download Excel",admin_nature_of_complaints2_path(params.merge(format: "xls")), :method=> :get, :class => "btn btn-primary"  %>
<table id="complaints">
	<thead>
		<tr>
			<th>Nature of Complaints</th>
			<th>Total</th>
		</tr>

	</thead>

	<tbody>
		<% @n1.each do |r| %>
		<tr>
			<td><%= r[0] %></td>
			<td><%= r[1] %></td>
		</tr>
		<% end %>
		

	</tbody>
</table>
</div>

 <% content_for :script do %>
 
  <%= javascript_include_tag "reports" %>

<script>
  $( document ).ready(function() {
	$("#other_type").hide();
	$("#nature").hide();
	$("#other_town").hide();

    function CheckOther()
{
  if (document.getElementById("report_industry_id").value == <%= Industry.last.id %>){
        $("#other_type").show();
    }     
    else{
       $("#other_type").hide();
    }     
}



function CheckOther2()
{
  if (document.getElementById("report_nature_of_review").value == "Other"){
        $("#nature").show();
    }     
    else{
       $("#nature").hide();
    }     
}

function CheckOther_town()
{
  if (document.getElementById("report_town_id").value == <%= Town.last.id + 1 %>){
        $("#other_town").show();
    }     
    else{
       $("#other_town").hide();
    }     
}
});


</script>
<% end %>

app/views/admin/reports/locations_by_town_and_company.js.erb
$("#report_location_id").html('<%= raw("<option></option>" +  options_for_select(@locations.map {|l| [l.title, l.id]}).gsub(/\n/, '') + "<option>Other</option>" ) %>');